### ISSUE TITLE
ID: S1 -  User registration

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#1]
## User Story:
As an unregistered user, I want to be able to register as a user with my chosen credentials (i.e., username and password that are both not empty words) to leverage/use services and information that are exclusively available to registered users.

## Acceptance criteria:
- [ ] Upon successful user registration, the home screen is shown, and the user is automatically logged in.
- [ ] Upon failure, an error is displayed, and the user is redirected (back) to the register screen.
- [ ] A register error can be that a username is already taken.
- [ ] The creation date of a user is saved to the database record.
- [ ] Logged-in users can log out and log back into their registered profile.

### Frontend
- [x] sopra-fs24-group-6/Client#1
- [x] sopra-fs24-group-6/Client#2
- [x] sopra-fs24-group-6/Client#3

### Backend
- [x] #83
- [x] #84
- [x] #85

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
