### ISSUE TITLE
ID: S11 - Voting mechanism

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#11]
## User story:
As a player, I want to be able to vote for the player I suspect to be in the minority at the end of the discussion time.

## Acceptance criteria:
- [ ] When the game's duration has ended, the screen will switch to one where you can choose the player to vote for.
- [ ] Before voting, the players can chat with each other on a game chat whilst making their decision on whom to vote.
- [ ] You can select the player you want to vote for (e.g., by using radio buttons or clicking on a username).
- [ ] By clicking the “Vote” button, it will be displayed that you have voted. If other players are still voting, this will also be displayed.

### Frontend
- [ ] sopra-fs24-group-6/Client#29
- [ ] sopra-fs24-group-6/Client#30
- [ ] sopra-fs24-group-6/Client#31
- [ ] sopra-fs24-group-6/Client#32
- [ ] sopra-fs24-group-6/Client#33

### Backend
- [x] #104
- [x] #105
- [x] #106
- [x] #163 

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
