### ISSUE TITLE
ID: S12 - Outcome of the rounds/game

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#12]
## User story:
As a player, I want to be able to see the results of everyone's votes and the outcome of the game.

## Acceptance criteria:
- [ ] Once everyone has finished voting, a results screen will be displayed.
- [ ] The results screen will show who voted for whom, the word assigned to each player, and the outcome for each player.
- [ ] A "Return to Home Screen" button is displayed, and by clicking it, you will be redirected to the home screen.

### Frontend
- [ ] sopra-fs24-group-6/Client#34
- [ ] sopra-fs24-group-6/Client#35
- [ ] sopra-fs24-group-6/Client#36
- [ ] sopra-fs24-group-6/Client#37
- [ ] sopra-fs24-group-6/Client#38

### Backend
- [x] #107
- [x] #108
- [ ] #109

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
