### ISSUE TITLE
ID: S14 - Friend requests & friend list

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#14]
## User story:
As a logged-in user, I want to be able to register other players as friends and view a list of the friends I have registered.

## Acceptance criteria:
- [ ] The "Add as a Friend" button is displayed next to each user in the user overview.
- [ ] When the "Add as a Friend" button is clicked, it will show as "Added".
- [ ] By clicking the "Friends" button on the home screen, a list of registered friends will be displayed.

### Frontend
- [ ] sopra-fs24-group-6/Client#41
- [ ] sopra-fs24-group-6/Client#42
- [ ] sopra-fs24-group-6/Client#43
- [ ] sopra-fs24-group-6/Client#44

### Backend
- [x] #112
- [x] #113
- [x] #114
- [x] #115

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
