### ISSUE TITLE
ID: S21 - Cohesive application

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#150]
## User story:
As a developer, I want my application to be cohesive in terms of style and looks.

## Acceptance criteria:
- [ ] All views should have a cohesive look and feel them
- [ ] Components for the views should be similar in style and looks

### Frontend
- [ ] sopra-fs24-group-6/Client#88
- [ ] sopra-fs24-group-6/Client#89
- [ ] sopra-fs24-group-6/Client#90
- [ ] sopra-fs24-group-6/Client#91
- [ ] sopra-fs24-group-6/Client#93
- [ ] sopra-fs24-group-6/Client#94
- [ ] sopra-fs24-group-6/Client#95
- [ ] sopra-fs24-group-6/Client#96
- [ ] sopra-fs24-group-6/Client#97
- [ ] sopra-fs24-group-6/Client#124
- [ ] sopra-fs24-group-6/Client#125
- [ ] sopra-fs24-group-6/Client#126
- [ ] sopra-fs24-group-6/Client#134
- [ ] sopra-fs24-group-6/Client#135

**Comment by Js18x** [comment]
All issues closed
