### ISSUE TITLE
ID: S16 - Custom theme

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#16]
## User story:
As a logged-in User, I want to be able to create a custom theme for the game.

## Acceptance criteria:
- [ ] When creating a lobby, in the theme selection setting a custom theme option should be available
- [ ] When selecting the custom theme option, I should be able to enter the desired words as well as the theme name

### Frontend
- [ ] sopra-fs24-group-6/Client#47
- [ ] sopra-fs24-group-6/Client#48
- [ ] sopra-fs24-group-6/Client#49
- [ ] sopra-fs24-group-6/Client#50

### Backend
- [ ] #119
- [ ] #120
- [ ] #121

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
