### ISSUE TITLE
ID: S17 - Automatic censoring 

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#17]
## User story:
As a logged-in User, I want the chat to automatically censor any inappropriate words I send or receive.

## Acceptance criteria:
- [ ] When an inappropriate chat message is sent, the displayed message should automatically be censored using an API.

### Frontend
- [ ] sopra-fs24-group-6/Client#51
- [ ] sopra-fs24-group-6/Client#52
- [ ] sopra-fs24-group-6/Client#53

### Backend
- [x] #122
- [x] #123
- [x] #124

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
