### ISSUE TITLE
ID: S22 WebSocket for communication

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#174]
As a user I want to be able to have real-time interaction with the other players in the game in order to receive real-time changes and chatting possibilities.

## Acceptance criteria:
- [ ] Users can see the settings updates done by the admin
- [ ] Users will be able to interact with each other

### Frontend
- [ ] sopra-fs24-group-6/Client#104
- [ ] sopra-fs24-group-6/Client#105
- [ ] sopra-fs24-group-6/Client#106
- [ ] sopra-fs24-group-6/Client#107
- [ ] sopra-fs24-group-6/Client#108
- [ ] sopra-fs24-group-6/Client#109
- [ ] sopra-fs24-group-6/Client#110
