### ISSUE TITLE
ID: S23 Use lobby management functionality with better user experience

### ISSUE THREAD

**Issue by kmkm0113** [sopra-fs24-group-6/Server#182]
As a logged-in user, I want to be able to use lobby management functionality smoothly in order to receive relevant information in real-time and be automatically processed in case of unexpected leaving.

## Acceptance criteria:
- [ ] When accessing the browser view, user is able to see all available lobbies with status
- [ ] When leaving lobby, user should be automatically removed from lobby
- [ ] When kicked by host, user should be notified and automatically navigated to menu view
- [ ] When lobby is updated, user is able to see its information in real-time

### Frontend
- [ ] sopra-fs24-group-6/Client#114
- [ ] sopra-fs24-group-6/Client#115
- [ ] sopra-fs24-group-6/Client#116
### Backend
- [ ] sopra-fs24-group-6/Server#183
- [ ] sopra-fs24-group-6/Server#184
- [ ] sopra-fs24-group-6/Server#185
- [ ] sopra-fs24-group-6/Server#186
