### ISSUE TITLE
ID: S2 - Profile visualisation & other user profiles

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#2]
## User story:
As a logged-in user, I want to inspect a registered user’s profile by selecting the username in a list of all registered users.

## Acceptance criteria:
- [ ] A user can view a list of all users in their own friends list and select each one for inspection.
- [ ] By clicking on a username in the users overview, you are redirected to a profile page of the selected user.
- [ ] The profile page contains the following data belonging to the selected user: username, online status, creation date, and birth date.
- [ ] The user overview and the profile page are only accessible for logged-in users.
- [ ] The birth date is optional and can only be set on the profile page.

### Frontend
- [x] sopra-fs24-group-6/Client#6
- [x] sopra-fs24-group-6/Client#5
- [x] sopra-fs24-group-6/Client#4

### Backend
- [x] #86
- [x] #87

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise

> [!CAUTION]
> Friends list implementation in a later user story so for now it is likely that we can only visualise the player's own profile
