### ISSUE TITLE
ID: S20 -  Guest user(player)

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#20]
## User story:
As a first-time player or casual player, I would want to be able to try out the game without having to register.

## Acceptance criteria:
- [ ] People can play the game without a registered profile
- [ ] People are given a “guest ID” that is usable for one session
- [ ] If a player is using this “guest ID” their score won’t count towards a leaderboard

### Frontend
- [ ] sopra-fs24-group-6/Client#58
- [ ] sopra-fs24-group-6/Client#59
- [ ] sopra-fs24-group-6/Client#60
- [ ] sopra-fs24-group-6/Client#61
- [ ] sopra-fs24-group-6/Client#62

### Backend
- [x] #130
- [x] #131

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
