### ISSUE TITLE
ID: S5 - Join games

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#5]
## User story:
As a logged-in user, I want to be able to search for and join games that have already been created.

## Acceptance criteria:
- [ ] By clicking the "Search for Game" button, a screen to set search criteria will be displayed.
- [ ] On the search criteria screen, you can set either a username or a game ID.
- [ ] By clicking the “Search” button, the games that match the criteria will be displayed. If the number of participants is less than the set number, a "Join" button will be displayed.
- [ ] By clicking the "Join" button for one of the search results games, you will be redirected to that game's game screen.

### Frontend
- [ ] sopra-fs24-group-6/Client#83
- [ ] sopra-fs24-group-6/Client#85
- [ ] sopra-fs24-group-6/Client#82
- [ ] sopra-fs24-group-6/Client#81
- [ ] sopra-fs24-group-6/Client#80
- [ ] sopra-fs24-group-6/Client#79
- [ ] sopra-fs24-group-6/Client#78
- [ ] sopra-fs24-group-6/Client#12
- [ ] sopra-fs24-group-6/Client#13
- [ ] sopra-fs24-group-6/Client#14
- [ ] sopra-fs24-group-6/Client#15
- [ ] sopra-fs24-group-6/Client#120

### Backend
- [x] sopra-fs24-group-6/Server#91
- [x] sopra-fs24-group-6/Server#92
- [x] sopra-fs24-group-6/Server#93

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
