### ISSUE TITLE
ID: S7 - Word assignment

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#7]
## User story:
As a player, I want to be assigned a word/theme and be able to see it when the game starts.

## Acceptance criteria:
- [ ] The word assigned to me will be displayed on the screen.
- [ ] Words assigned to other players cannot be seen.

### Frontend
- [ ] sopra-fs24-group-6/Client#17
- [ ] sopra-fs24-group-6/Client#18
- [ ] sopra-fs24-group-6/Client#86
- [ ] sopra-fs24-group-6/Client#87

### Backend
- [ ] sopra-fs24-group-6/Server#95
- [ ] #96

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
