### ISSUE TITLE
ID: S8 - Chat funtionality

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#8]
## User story:
As a player, I want to be able to send chats for questioning and discussing.

## Acceptance criteria:
- [ ] You can enter text into an input field.
- [ ] By pressing the “Send” button, you can send the text you entered to other players.
- [ ] Chats you send will be displayed on the game screen in real-time.

### Frontend
- [ ] sopra-fs24-group-6/Client#19
- [ ] sopra-fs24-group-6/Client#20
- [ ] sopra-fs24-group-6/Client#21

### Backend
- [x] #97
- [x] #98

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
