### ISSUE TITLE
ID: S9 - Chat translation

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#9]
## User story:
As a player, I want to be able to see chats sent by other players translated into my selected language in (quasi) real-time.

## Acceptance criteria:
- [ ] Chats sent by other players will be displayed on my game screen within a few seconds after being sent (Note: this is subject to processing and communication time of external translation API).
- [ ] The chats will be translated into the language I have selected.

### Frontend
- [ ] sopra-fs24-group-6/Client#22
- [ ] sopra-fs24-group-6/Client#23
- [ ] sopra-fs24-group-6/Client#24
- [ ] sopra-fs24-group-6/Client#25

### Backend
- [x] #99
- [x] #100
- [ ] #101

> [!NOTE]  
> Complementary tasks such as correct navigation and creation of necessary components are implied unless specified otherwise
